### ISSUE TITLE
stacked bar: final transition

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#13]

**Comment by jadiehm** [comment]
I talked to Russell about this one and here's what we think the order of operations should be:

- Country columns disappear
- Column titles are renamed
- Bars shift

There's a start to that in `stackedBar.js` inside the `renderThemeBars` function. It's currently a hack of a bunch of timeouts. Feel free to change! It is semi-working, just not elegantly, and the height of the bars on transition is wonky (see their original version in the `dev-new` branch.

THEN, all of these things need to revert again on scroll up. Those scrollytelling triggers are housed in `stackedBar.js` inside the `updateChart` function. That `updateChart` function is then called in `graphicX.js` inside `renderStep` on line 85.

**Comment by mmcghee18** [comment]
- [ ] revert on scroll up
- [ ] fade instead of disappear
- [ ] bar heights
