### ISSUE TITLE
stacked bar: remove rects with no data

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#49]

**Comment by robsmithwashere** [comment]
As seen in the screenshot here, the word man should be highlighted in black at the top of each stacked bar. instead rectangles with no data appear first.  @lnicoletti may have a fix for it. 

<img width="897" alt="Screen Shot 2021-12-15 at 10 32 25 AM" src="https://user-images.githubusercontent.com/88445968/146215943-54e3ed03-b445-40ca-bdab-4e122d01f9db.png">

**Comment by jadiehm** [comment]
This is happening because there are currently holes in the data like so:

**country, word, rank**
all, kill, 3
india, kill, null
south africa, kill, 5
uk, kill, 10
us, kill, 6

For rectangles without a value (i.e. that word falls outside of the top 200 terms for that country), they are being placed on top. We need to not show them at all. That's currently happening in `stackedBar.js` inside the `resize` function. The y position of the rectangles is being set on line 494. Might be as simple as giving the rects where `d.data[d.key.word] === null` an `attr` of `display: none`...?
