### ISSUE TITLE
temporal chart: match tooltips on word

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#50]

**Comment by jadiehm** [comment]
This is for when you hover over the area charts. The headline it picks should include the associated word. Currently that is supposed to happen in `temporalLine.js` inside the `showTooltip` function on line 165. `wordHeadlines` is supposed to filter, but it's not working correctly.

**Comment by SahitiSarva** [comment]
![Word highlight temporal](https://user-images.githubusercontent.com/55742994/146350928-34f2e704-80ab-41b9-9a9e-1d2dd92efd98.png)
It should potentially look something like this. Our version of the code is available in dev-new in case that is useful!
