### ISSUE TITLE
tooltips: multiple headlines + positioning

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#51]

**Comment by jadiehm** [comment]
The goal is to just get these closer to there event positions. Positioning for tooltips can be found:

- In `bubble.js` inside `showTooltip` function on line 159
- In `temporalLine.js` inside `showTooltip` function on line 165

**Comment by SahitiSarva** [comment]
![Temporal event tooltip](https://user-images.githubusercontent.com/55742994/146403346-06d827ed-7526-4b3d-ac5d-543119f90bc6.png)
Currently it looks something like this where the event is slightly higher up and to the left. The idea is to move the tooltip closer to the bubble.

**Comment by SahitiSarva** [comment]
The bubble chart tooltip also has tooltips slightly more to the left and higher up from the bubble itself (like in the image below)
![Bubble tooltip bug](https://user-images.githubusercontent.com/55742994/146405374-59777692-40e4-41e8-84e7-e08af5fcbe76.png)
 
 But the tooltips need to be adjusted (maybe something like the below image)
![Bubble tooltip fixed](https://user-images.githubusercontent.com/55742994/146405893-91dfded7-2f5d-4b01-867c-6acd0e213d2f.png)
