### ISSUE TITLE
mobile: checks

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#52]

**Comment by SahitiSarva** [comment]
The bubble charts seem a bit squished on mobile 
![squished bubble mobile](https://user-images.githubusercontent.com/55742994/146406382-92077d59-fcba-4afb-9f83-9d537f6e690b.jpeg)

The top of the scrolly is cut off 
![scrolly top cutoff](https://user-images.githubusercontent.com/55742994/146406409-745654f6-c2a8-4908-91bf-52653232a203.jpeg)

The scales in the temporal chart are slightly off (the chart is too high)
![too long temporal waves](https://user-images.githubusercontent.com/55742994/146406555-140ea957-0331-44c4-a7c0-e60b8cea0eb8.jpeg)
