### ISSUE TITLE
stacked bar: height

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#55]

**Comment by jadiehm** [comment]
Need the first rectangles to fill the height of the svg. Currently svg height is being set inside `stackedBar.js` inside `resize` function on line 434. Rectangle height is set on line 492.

**Comment by SahitiSarva** [comment]
Currently, the stacked bar doesn't occupy the entire screen size on desktop. 

![scrolly size](https://user-images.githubusercontent.com/55742994/146407172-07227ae1-61be-4aad-aba0-1063f4291920.png)
