### ISSUE TITLE
temporal chart: tooltip on right

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/women-in-headlines#57]

**Comment by robsmithwashere** [comment]
when you hover over the dots (forgive the informal terminology) that appear above this temporal chart, details about an historic event pop up.  Those pop ups should appear to the right of the chart. 

<img width="1271" alt="Screen Shot 2021-12-15 at 10 35 41 AM" src="https://user-images.githubusercontent.com/88445968/146216416-494aa1c7-9460-4992-8cdb-2fbad82e0232.png">

**Comment by jadiehm** [comment]
Currently being positioned inside `temporalLine.js` with `showTooltip` function on line 179.

**Comment by jadiehm** [comment]
Idea: position near where hovering. Remove italics from text so that it's not the same style as a headline tooltip. Then before the date: maybe just write `EVENT: ${date}`. Line 240.
