### ISSUE TITLE
Tooltip in temporal chart doesn't show after filtering 

### ISSUE THREAD

**Issue by SahitiSarva** [the-pudding/women-in-headlines#65]
When the temporal chart is filtered based on country, the tooltip stops showing 

![No tooltip after filter](https://user-images.githubusercontent.com/55742994/147055384-18923fa2-e77b-40f4-b7e4-6e2ab3af7e3e.png)

Also, when there is not filter, the tooltip only shows one headline for the first place where the user hovers. The headline doesn't change if the user moves across the trajectory

![Temporal chart not changing tooltip](https://user-images.githubusercontent.com/55742994/147055398-ccad97c5-4ad9-42a0-8837-df1886e3e511.png)

**Comment by mmcghee18** [comment]
Fixed the first thing. The second thing would be nice, but will require more work since it's not currently set up to work like that. Right now, it's built to just pick a random headline containing that word.
