### ISSUE TITLE
Bar opacity is different for different bars

### ISSUE THREAD

**Issue by SahitiSarva** [the-pudding/women-in-headlines#71]
The opacity of the bars seems different for different words. Would we know why?

Could we increase the size of these bars just by a little bit? (attached a screenshot of how it used to be)

![image](https://user-images.githubusercontent.com/55742994/148195757-e234a2d4-9f5d-48d4-8f8e-b85e7466f1fc.png)

Previous bar width

![image](https://user-images.githubusercontent.com/55742994/148196257-1dbc90ce-56f6-4fbe-869f-a568a0fb986d.png)

**Comment by mmcghee18** [comment]
Re: opacity

I'm not seeing the issue you're seeing. I see all of the colored ones having the same opacity when calling out a theme:
![image](https://user-images.githubusercontent.com/16782770/148584541-05d24183-f3e8-4067-a98b-e9d3bcf6e45d.png)

And then different opacities here to call out a word
![image](https://user-images.githubusercontent.com/16782770/148584619-63839834-5987-435a-a4b0-070af827be27.png)

If you still feel like there's an opacity issue, can you be more specific with where you're seeing it and what should be different?
